name: Push-to-EC2
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
jobs:
  node:
    runs-on: [ self-hosted, development ]
    steps:
    - name: Checkout the code
      uses: actions/checkout@v1
    - name: Deploy to my EC2 instance
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        REMOTE_HOST: "52.15.103.231"
        REMOTE_USER: "ubuntu"
        TARGET: "/home/ubuntu/"
    - run: pwd
    - run: sudo cp /home/ubuntu/Dockerfile ./
    - run: sudo cp /home/ubuntu/dev.env ./
    - run: ls
    - name: Run build
      run: |
        sudo docker stop rexnet-dev || true
        sudo docker rm rexnet-dev  || true
        sudo docker rmi rexnet-dev  || true
        sudo docker build -t rexnet-dev .
        sudo docker run --name rexnet-dev -d -p 80:80 rexnet-dev
